# fly.toml file generated for summer-sun-567 on 2022-08-10T01:41:57+05:00

app = "summer-sun-567"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]
  PHX_HOST = "summer-sun-567.fly.dev"
  PORT = "4000"

[deploy]
  release_command = "/blogs/bin/migrate"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
